"""
PDF Generator Agent — port 8009

Renders a curated day-by-day itinerary (produced by the Trip Planner agent)
into a polished PDF travel guide. Layout:

  - Cover page          : video source, thumbnail, trip date, total cost
  - One page per day    : theme, day cost, each stop with activity, duration,
                          address, GPS, and nearby restaurants
  - Final maps page     : full Google Maps road-trip link
"""

import os
import requests  # type: ignore[import-untyped]
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime
from io import BytesIO
from dotenv import load_dotenv
from openai import OpenAI
from fpdf import FPDF
from fpdf.enums import XPos, YPos
from uagents import Agent, Context
from shared_models import PDFRequest, PDFResponse

# fpdf2 deprecated `ln=True` in v2.5.2. These kwargs reproduce the old
# behaviour (advance to the next line at the left margin).
_NEWLINE = dict(new_x=XPos.LMARGIN, new_y=YPos.NEXT)

load_dotenv()
os.makedirs("output", exist_ok=True)

agent = Agent(
    name="pdf_generator_agent",
    seed=os.getenv("PDF_SEED"),
    port=8009,
    endpoint=[os.getenv("PDF_GENERATOR_ENDPOINT", "http://localhost:8009/submit")],
    network="testnet",
)

asi1_client = OpenAI(
    base_url="https://api.asi1.ai/v1",
    api_key=os.getenv("ASI1_API_KEY"),
)

TEAL_R, TEAL_G, TEAL_B = 30, 158, 117
LIGHT_R, LIGHT_G, LIGHT_B = 242, 250, 246
CORAL_R, CORAL_G, CORAL_B = 245, 196, 179
DARK_R, DARK_G, DARK_B = 25, 50, 40

# fpdf2's built-in Helvetica is Latin-1 only. ASI:One LLM descriptions and
# YouTube titles routinely contain em dashes, smart quotes, ellipses, etc.
# Normalise everything before writing it to the PDF.
_UNICODE_FIXUPS = str.maketrans(
    {
        "\u2014": "-",  # em dash
        "\u2013": "-",  # en dash
        "\u2212": "-",  # minus sign
        "\u2018": "'",  # left single quote
        "\u2019": "'",  # right single quote / apostrophe
        "\u201c": '"',  # left double quote
        "\u201d": '"',  # right double quote
        "\u2026": "...",  # horizontal ellipsis
        "\u00a0": " ",  # non-breaking space
        "\u2022": "-",  # bullet
        "\u2028": " ",  # line separator
        "\u2029": " ",  # paragraph separator
    }
)


def _pdf_safe(text) -> str:
    """Return a Latin-1-safe version of *text* for fpdf2's core fonts."""
    if text is None:
        return ""
    s = str(text).translate(_UNICODE_FIXUPS)
    return s.encode("latin-1", "replace").decode("latin-1")


def get_stop_description(place_name: str) -> str:
    try:
        response = asi1_client.chat.completions.create(
            model="asi1-mini",
            max_tokens=120,
            temperature=0.7,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a travel writer. Write vivid, specific "
                        "2-sentence descriptions of destinations. "
                        "Be concrete - mention what makes each place unique."
                    ),
                },
                {
                    "role": "user",
                    "content": (
                        f"Write a 2-sentence traveller's description of {place_name}. "
                        "Be specific and evocative."
                    ),
                },
            ],
        )
        return response.choices[0].message.content.strip()
    except Exception:
        return f"{place_name} - a must-visit stop on your road trip."


def download_thumbnail(url: str):
    try:
        resp = requests.get(url, timeout=10)
        if resp.status_code == 200:
            return BytesIO(resp.content)
    except Exception:
        pass
    return None


class TravelPDF(FPDF):
    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(
            0,
            10,
            _pdf_safe("Generated by Travel Map Agent on ASI:One - Fetch.ai Agentverse"),
            align="C",
        )


def _render_cover_page(pdf: "TravelPDF", msg: PDFRequest) -> None:
    pdf.add_page()

    # header strip
    pdf.set_fill_color(TEAL_R, TEAL_G, TEAL_B)
    pdf.rect(0, 0, 210, 60, "F")

    pdf.set_y(10)
    pdf.set_font("Helvetica", "B", 24)
    pdf.set_text_color(255, 255, 255)
    title = _pdf_safe(msg.trip_title or "Road Trip Itinerary")
    pdf.cell(0, 12, title, align="C", **_NEWLINE)

    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(200, 240, 220)
    total_stops = sum(len(d.get("stops", [])) for d in msg.planned_days)
    pdf.cell(
        0,
        9,
        _pdf_safe(
            f"Trip date: {msg.trip_start_date}  |  "
            f"{len(msg.planned_days)} day{'s' if len(msg.planned_days) != 1 else ''}  |  "
            f"{total_stops} stops  |  "
            f"est. ${msg.total_estimated_cost:.0f}"
        ),
        align="C",
        **_NEWLINE,
    )

    # video source credit
    if msg.video_title or msg.channel_name:
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(180, 230, 210)
        source = f"Based on: {msg.video_title or ''}"
        if msg.channel_name:
            source += f" by {msg.channel_name}"
        pdf.cell(0, 8, _pdf_safe(source), align="C", **_NEWLINE)

    # thumbnail image if available
    thumb_y = 72
    if msg.thumbnail_url:
        img_data = download_thumbnail(msg.thumbnail_url)
        if img_data:
            try:
                pdf.image(img_data, x=55, y=thumb_y, w=100)
                thumb_y += 60
            except Exception:
                pass

    # intro text
    pdf.set_y(thumb_y + 8)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(50, 50, 50)
    pdf.set_x(18)
    pdf.multi_cell(
        174,
        7,
        _pdf_safe(
            "This itinerary was autonomously generated by a multi-agent "
            "system running on Fetch.ai's Agentverse platform. Locations "
            "were extracted from a YouTube travel vlog, validated against "
            "Google Places, curated into a realistic day-by-day plan by "
            "ASI1 LLM, and enriched with nearby restaurant suggestions. "
            "A weather monitor agent is actively watching all stops and "
            "will alert you if conditions change."
        ),
    )

    if msg.preferences:
        pdf.ln(4)
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(TEAL_R, TEAL_G, TEAL_B)
        pdf.set_x(18)
        pdf.cell(0, 7, "Your preferences:", **_NEWLINE)
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(50, 50, 50)
        pdf.set_x(18)
        pdf.multi_cell(174, 7, _pdf_safe(msg.preferences))

    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(TEAL_R, TEAL_G, TEAL_B)
    pdf.set_x(18)
    pdf.cell(0, 8, "Itinerary at a glance:", **_NEWLINE)

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(50, 50, 50)
    for day in msg.planned_days:
        pdf.set_x(18)
        line = (
            f"  Day {day.get('day_number', '?')} - {day.get('theme', '')}"
            f"   (${day.get('estimated_cost_usd', 0):.0f}, "
            f"{len(day.get('stops', []))} stops)"
        )
        pdf.cell(0, 7, _pdf_safe(line), **_NEWLINE)


def _format_forecast_line(forecast: dict) -> str:
    """One-line human-friendly summary of a stop's trip-date forecast."""
    if not forecast or not forecast.get("available"):
        return "Forecast: not yet available for this date"

    parts = []
    cond = forecast.get("condition") or ""
    if cond:
        parts.append(cond)

    high = forecast.get("high_c")
    low = forecast.get("low_c")
    if high is not None and low is not None:
        parts.append(f"{high:.0f}/{low:.0f} C")
    elif high is not None:
        parts.append(f"H {high:.0f} C")

    precip = forecast.get("precip_percent", 0) or 0
    if precip:
        parts.append(f"{precip}% rain")

    thunder = forecast.get("thunderstorm_percent", 0) or 0
    if thunder >= 20:
        parts.append(f"{thunder}% storms")

    wind = forecast.get("wind_kmh", 0) or 0
    if wind >= 20:
        parts.append(f"wind {wind:.0f} km/h")

    line = (
        "Forecast: " + " | ".join(parts) if parts else "Forecast: details unavailable"
    )
    if forecast.get("bad") and forecast.get("warning"):
        line += f"  [!] {forecast['warning']}"
    return line


def _render_day_page(
    pdf: "TravelPDF",
    day: dict,
    descriptions: dict,
    preferences: str,
    initial_forecasts: dict,
) -> None:
    """Render one full page for one planned day."""
    pdf.add_page()

    # day header strip
    pdf.set_fill_color(CORAL_R, CORAL_G, CORAL_B)
    pdf.rect(0, 0, 210, 24, "F")
    pdf.set_y(5)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(153, 60, 29)
    header = (
        f"DAY {day.get('day_number', '?')}  -  "
        f"{day.get('theme', '').upper()}  -  "
        f"EST. ${day.get('estimated_cost_usd', 0):.0f}"
    )
    pdf.cell(0, 14, _pdf_safe(header), align="C", **_NEWLINE)

    pdf.set_y(30)

    stops = day.get("stops", [])
    for stop_idx, stop in enumerate(stops, 1):
        if pdf.get_y() > 240:
            pdf.add_page()
            pdf.set_y(20)

        # stop name
        pdf.set_x(15)
        pdf.set_font("Helvetica", "B", 15)
        pdf.set_text_color(DARK_R, DARK_G, DARK_B)
        name = stop.get("name", "")
        if len(name) > 40:
            name = name[:38] + "..."
        pdf.cell(0, 9, _pdf_safe(f"{stop_idx}. {name}"), **_NEWLINE)

        # activity + duration line
        if stop.get("activity") or stop.get("duration_hours"):
            pdf.set_x(15)
            pdf.set_font("Helvetica", "I", 10)
            pdf.set_text_color(TEAL_R, TEAL_G, TEAL_B)
            activity = stop.get("activity", "") or "visit"
            duration = stop.get("duration_hours", 0)
            line = f"{activity}  -  ~{duration}h" if duration else activity
            pdf.cell(0, 6, _pdf_safe(line), **_NEWLINE)

        # address + GPS
        pdf.set_x(15)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(110, 110, 110)
        pdf.cell(0, 5, _pdf_safe(stop.get("address", "")), **_NEWLINE)
        pdf.set_x(15)
        pdf.cell(
            0,
            5,
            f"GPS: {stop.get('lat', 0):.5f}, {stop.get('lng', 0):.5f}",
            **_NEWLINE,
        )
        pdf.ln(1)

        # description (ASI1-generated, pre-fetched)
        description = descriptions.get(stop.get("name", ""), "")
        if description:
            pdf.set_x(15)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(55, 55, 55)
            pdf.multi_cell(180, 6, _pdf_safe(description))

        # initial forecast from the weather agent
        forecast = initial_forecasts.get(stop.get("name", "")) or {}
        if forecast:
            pdf.ln(1)
            pdf.set_x(15)
            pdf.set_font("Helvetica", "B", 9)
            # Colour bad-forecast lines red, good ones teal.
            if forecast.get("bad"):
                pdf.set_text_color(180, 40, 40)
            else:
                pdf.set_text_color(15, 110, 86)
            pdf.multi_cell(180, 5, _pdf_safe(_format_forecast_line(forecast)))

        # nearby restaurants
        restaurants = stop.get("nearby_restaurants") or []
        if restaurants:
            pdf.ln(1)
            pdf.set_x(15)
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(15, 110, 86)
            label = "Nearby restaurants"
            if preferences:
                label += f" ({preferences[:40]})"
            pdf.cell(0, 5, _pdf_safe(label + ":"), **_NEWLINE)

            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(70, 70, 70)
            for r in restaurants:
                pdf.set_x(18)
                rating = r.get("rating", 0) or 0
                star = f" ({rating:.1f}*)" if rating else ""
                line = f"- {r.get('name', '')}{star}  -  {r.get('address', '')}"
                pdf.multi_cell(175, 5, _pdf_safe(line))

        pdf.ln(3)
        pdf.set_draw_color(220, 220, 220)
        pdf.line(15, pdf.get_y(), 195, pdf.get_y())
        pdf.ln(4)


def _render_maps_page(pdf: "TravelPDF", msg: PDFRequest) -> None:
    pdf.add_page()

    pdf.set_fill_color(TEAL_R, TEAL_G, TEAL_B)
    pdf.rect(0, 0, 210, 30, "F")
    pdf.set_y(8)
    pdf.set_font("Helvetica", "B", 17)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 14, "Your Google Maps Road Trip", align="C", **_NEWLINE)

    pdf.set_y(44)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(55, 55, 55)
    pdf.set_x(15)
    pdf.multi_cell(
        175,
        7,
        _pdf_safe(
            "Open the link below in any browser or on your phone. "
            "All stops are pre-loaded in driving order."
        ),
    )

    pdf.ln(5)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(TEAL_R, TEAL_G, TEAL_B)
    pdf.set_x(15)
    pdf.cell(0, 8, "Road trip link:", **_NEWLINE)

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(30, 80, 180)
    pdf.set_x(15)
    pdf.multi_cell(175, 6, _pdf_safe(msg.maps_url))

    pdf.ln(8)
    pdf.set_draw_color(210, 210, 210)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(6)

    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(140, 140, 140)
    pdf.set_x(15)
    pdf.multi_cell(
        175,
        6,
        _pdf_safe(
            "This itinerary was created by an autonomous multi-agent system on "
            "Fetch.ai Agentverse. Agents used: Transcript Agent, Location "
            "Extractor Agent (ASI1 LLM), Geocoder + Mapper Agent, Trip Planner "
            "Agent (ASI1 LLM + Google Places), PDF Generator Agent (ASI1 LLM), "
            "Weather Monitor Agent (Google Weather API)."
        ),
    )


def generate_pdf(msg: PDFRequest) -> tuple[str, str]:
    pdf = TravelPDF()
    pdf.set_auto_page_break(auto=True, margin=20)

    _render_cover_page(pdf, msg)

    # Pre-fetch all ASI:One descriptions in parallel. Sequential would
    # take ~1-2s per stop; parallelising keeps total latency well within
    # the orchestrator's PDF timeout.
    all_stops = [stop for day in msg.planned_days for stop in day.get("stops", [])]
    stop_names = [stop.get("name", "") for stop in all_stops]
    with ThreadPoolExecutor(max_workers=8) as pool:
        descriptions_list = list(pool.map(get_stop_description, stop_names))
    descriptions = dict(zip(stop_names, descriptions_list))

    initial_forecasts = msg.initial_forecasts or {}
    for day in msg.planned_days:
        _render_day_page(
            pdf,
            day,
            descriptions,
            msg.preferences or "",
            initial_forecasts,
        )

    _render_maps_page(pdf, msg)

    filename = f"itinerary_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    filepath = os.path.join("output", filename)
    pdf.output(filepath)
    return filename, os.path.abspath(filepath)


@agent.on_message(PDFRequest)
async def handle_pdf(ctx: Context, sender: str, msg: PDFRequest):
    total_stops = sum(len(d.get("stops", [])) for d in msg.planned_days)
    ctx.logger.info(
        f"Generating PDF for {len(msg.planned_days)} day(s), {total_stops} total stops"
    )
    try:
        filename, filepath = generate_pdf(msg)
        ctx.logger.info(f"PDF saved: {filepath}")
        await ctx.send(
            sender,
            PDFResponse(
                success=True,
                pdf_filename=filename,
                pdf_path=filepath,
            ),
        )
    except Exception as e:
        ctx.logger.error(f"PDF generation error: {e}")
        await ctx.send(
            sender,
            PDFResponse(
                success=False,
                error=str(e),
            ),
        )


if __name__ == "__main__":
    agent.run()
